version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Cont4bl3Secure@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend

  contabilidad-springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contabilidad-springboot
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  sql_data:

networks:
  backend:
