version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Cont4bl3Secure@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
    restart: always

  contabilidad-springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contabilidad-springboot
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    external: true
